# Generated by Django 6.0.4 on 2026-05-09 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('email_id', models.EmailField(max_length=100, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('user_image_url', models.ImageField(upload_to='profile_photo')),
                ('password', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=150)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image_url', models.ImageField(upload_to='product_photo')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='campusXmart.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='campusXmart.user')),
            ],
        ),
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('fraud_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_fraud', models.CharField(blank=True, max_length=100, null=True)),
                ('any_evidence', models.FileField(blank=True, null=True, upload_to='report_evidence')),
                ('description', models.TextField(blank=True, null=True)),
                ('report_issue_date', models.DateTimeField(auto_now_add=True)),
                ('report_status', models.CharField(default='submitted', max_length=50)),
                ('verification_status', models.CharField(default='pending', max_length=50)),
                ('reported', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to='campusXmart.user')),
                ('reportee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to='campusXmart.user')),
            ],
        ),
    ]
